linters:
  enable:
    - gofmt
    - goimports
    - gocyclo
    - revive
    - goconst
    - misspell
    - unconvert
    - gocritic
    - prealloc
    - copyloopvar
    - gosec
    - lll

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain

issues:
  max-issues-per-linter: 50

run:
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly
