---
name: Lines of code
on:
  push:
    branches:
      - master
jobs:
  loc-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          debug: true
          directory: .
          badge: output/loc-badge.svg
      - uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: output
          clean: false
        if: github.ref == 'refs/heads/master'
